import { Inter } from 'next/font/google'
import './globals.css'
import { Suspense } from 'react'
import Loading from './loading'
import CommonLayout from '@/components/common-layout'
import { ClerkProvider } from '@clerk/nextjs'
import { Toasterr } from '@/components/ui/toaster'
import Footer from '@/components/footer'
import { Analytics } from '@vercel/analytics/react'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Workwise',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={inter.className}>
          <Suspense fallback={<Loading />}>
            <CommonLayout
              attribute='class'
              defaultTheme='system'
              children={children}
            />
            <Footer />
          </Suspense>
          <Toaster />
          <Toasterr />
        </body>
        <Analytics />
      </html>
    </ClerkProvider>
  )
}
